post/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    path('', views.post_create, name='create'),
    path('feed/', views.feed, name='feed'),
    path('like/', views.like_post, name='post_like'),
    
]

social_media/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('post/', include('post.urls'))
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from re import template
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_view


app_name = 'user'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', auth_view.LoginView.as_view(template_name = 'user/login.html'), name='login'),
    path('logout/',auth_view.LogoutView.as_view(template_name = 'user/logout.html'),name='logout'),
    path('password_change_form/',auth_view.PasswordChangeView.as_view(template_name = 'user/password_change_form.html'),name='password_change_form'),
    path('password_change_done/',auth_view.PasswordChangeDoneView.as_view(template_name = 'user/password_change_done.html'),name='password_change_done'),
    path('password_reset/', auth_view.PasswordResetView.as_view(template_name='user/password_reset_form.html',
                                                                email_template_name='user/password_reset_email.html',
                                                                subject_template_name='user/password_reset_subject.txt',
                                                                success_url=reverse_lazy('user:password_reset_done'),
                                                                ),name='password_reset'),
    path('password_reset_done/', auth_view.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html',
                                                                success_url = reverse_lazy('user:password_reset_complete') 
                                                                ),name='password_reset_confirm'),
    path('reset/done/', auth_view.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'), name='password_reset_complete'),

    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
]

post/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify

# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/posts')
    caption = models.TextField(blank=True)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    created = models.DateField(auto_now_add=True)
    like_by = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='post_liked' , blank= True)

    def __str__(self):
        return self.title
    
    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug  = slugify(self.title)
        super().save(*args,**kwargs)

class Comments(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='comment')
    body = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now=True)
    posted_by = models.CharField(max_length=100)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return self.body

user/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='users/images/profile',blank=True)

    

post/forms.py
from .models import Post, Comments
from django import forms

class PostCreateForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title','image','caption']

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comments
        fields = ['body','posted_by']

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','email']

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['photo']

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

post/views.py
from termios import OPOST
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from .forms import PostCreateForm, CommentForm
from django.contrib.auth.decorators import login_required

from .models import Post
from user.models import Profile
# Create your views here.

@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostCreateForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            # Redirect to a success page or any other appropriate action
            return redirect('user:index')
    else:
        form = PostCreateForm(data=request.GET)
        
    return render(request, 'post/create.html', {'form': form})

@login_required
def feed(request):
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        new_comment = comment_form.save(commit=False)
        post_id = request.POST.get('post_id')
        post = get_object_or_404(Post,id=post_id)
        new_comment.post = post
        new_comment.save()
    else:
        comment_form = CommentForm()


    posts = Post.objects.all()
    logged_user = request.user
    return render(request, 'post/feed.html', {'posts': posts,'logged_user':logged_user,'comment_form':comment_form})


def like_post(request):
    post_id = request.POST.get('post_id')
    post = get_object_or_404(Post,id=post_id)
    if post.like_by.filter(id =request.user.id).exists():
        post.like_by.remove(request.user)
    else:
        post.like_by.add(request.user)

    return redirect('post:post_like')

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import RegistrationForm, UserEditForm,ProfileEditForm
from .models import Profile
from post.models import Post


@login_required
def index(request):
    current_user = request.user
    posts = Post.objects.filter(user = current_user)
    profile = Profile.objects.filter(user=current_user).first()
    return render(request, 'user/index.html',{'posts':posts,'profile':profile})


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit= False)
            new_user.save()
            Profile.objects.create(user = new_user)
            return redirect('user:login')
    else:
        form = RegistrationForm()
    return render(request, 'user/register.html', {'form': form})

@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('user:index')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    
    return render(request, 'user/edit.html', {'user_form': user_form, 'profile_form': profile_form})

post/templates/post/create.html
{% extends 'user/base.html' %}
{% block body %}
<h1 class="text-2xl m-5 font-bold">Post</h1>
<div class="container py-5 ">
    <form method="POST" class="bg-white shadow-md m-10 rounded px-2  pd-8 mb-4" enctype="multipart/form-data">
        {%csrf_token%}
        <div class="mb-3">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Title</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10">{{form.title}}</div>
        </div>
        <div class="mb-3">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Upload Image</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10">{{form.image}}</div>
        </div>
        <div class="mb-3">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Caption</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10">{{form.caption}}</div>
        </div>
        
        <button type="submit"class="text-white bg-green-500 px-5 py-2 mb-3">Post</button>
    </form>
    
</div>

{% endblock %}

post/templates/post/feed.html
{% extends 'user/base.html' %}
{% load mathfilters %}
{% load static %}
{% block body %}
    <div class="flex mt-5 p-5 justify-center">
        <h2 class="text-3xl font-normal mb-2 text-green-500">My Post</h2>
    </div>

    <div class="grid mx-60 p-10 grid-cols-1">
        <!-- card start from here -->
        {% for post in posts %}
            <a href="#">
                <div class="rounded overflow-hidden w-[470px] bg-white shadow-lg">
                    <div class="user-container flex mx-5 my-5">
                        {% if post.user.profile.photo %}
                            <img src="{{ post.user.profile.photo.url }}" alt="" class="h-12 w-12 rounded-full" >
                        {% else %}
                            <img src="" alt="">
                        {% endif %}
                        <div class="mx-2 my-2 font-bold">
                            <span class="text-indigo-500">{{post.user}}</span>
                        </div>
                    </div>
                    <div >
                        <img src="{{post.image.url}}" alt="">
                    </div>
                    <div class="px-6 py-4">
                        <div class="icon-container flex gap-3">
                            <a id="{{post.id}}" class="btn-like">
                                {% if logged_user in post.like_by.all %}
                                    <img class="w-5 h-5" src="{% static 'user/images/redlike.png' %}" alt="">
                                {% else %}
                                    <img class="w-5 h-5" src="{% static 'user/images/like.png' %}" alt="">
                                {% endif %}
                            </a>
                           
                            <img class="w-5 h-5" src="{% static 'user/images/comment.png' %}" alt="">
                            <img class="w-5 h-5" src="{% static 'user/images/share.png' %}" alt="">
                        </div>
                        <div>
                            <p>
                                {% if post.like_by.count < 1 %}
                                {% elif post.like_by.count == 1 %}
                                {{ post.like_by.first }} Liked this
                                {% elif post.like_by.count > 1 %}
                                {{ post.like_by.first }} & {{post.like_by.count|sub:1 }} Others Liked this
                                {% endif %}
                            </p>
                        </div>
                    </div>
                </div>
                
                <div class="px-6 py-4">
                    <div class="font-bold text-xl mb-2">
                        {{post.title}}
                    </div>
                    <p class="text-gray-700 text-base">
                        {{post.caption}}
                    </p>
                </div>
                <div class="px-5 py-5">
                    {% for comment in post.comment.all %}
                       <b>{{ comment.posted_by }} </b> {{ comment.body }}
                        <br>
                    {% endfor %}
                </div >
                <div class="px-5 py-5">
                    <form action="" method="POST" class="bg-white rounded px-6 pt-6 pb-8 mb-8">
                        {%csrf_token%}
                        <div class="flex">
                            <div class="shadow appearance-none rounded py-2 px-3 mr-10 text-gray-700">
                                {{comment_form.body}}
                            </div>
                            <input type="hidden" name="post_id" id="post_id" value="{{post.id}}">
                            <input type="hidden" name="posted_by" id="posted_by" value="{{logged_user}}">
                            
                            <button type="submit" class="bg-green-500 text-white px-5 py-2">Submit</button>
                        </div>
                        
                    </form>
                </div>
                
            </a>

        {%endfor%}
        <!-- card end here -->
    </div>
    <script>
        window.CSRF_TOKEN = "{{ csrf_token }}"
        $(document).on('click','.btn-like',function(){
            console.log(this.id)
            var post_id = this.id
            $.ajax({
                method: "POST",
                url: '/post/like/',
                data: {post_id: post_id, csrfmiddlewaretoken: window.CSRF_TOKEN}
            });
            window.location.href="http://127.0.0.1:8000/post/feed/"
        })
    </script>

{% endblock %}



       
    

user/templates/user/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'user/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.js"></script>
</head>
<body>

    <nav class="shadow-2xl ">
        <div class="px-4 mx-auto">
            <div class="flex justify-between">
                <!-- website logo -->
                <div>   
                    <a class="flex" href="{% url 'user:index' %}">
                        <img class="h-12 w-12 mr-2" src="{% static 'user/images/logo.png' %}" alt="">
                        <span class="font-semibold text-lg text-gray-500 ">Photo App</span>
                    </a>
                </div>
                <!-- website item -->
                <div class="space-x-1">
                    {% if request.user.is_authenticated %}
                    <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'user:logout' %}">Logout</a>
                    <a href="{% url 'user:password_change_form' %}">Change Password</a>
                    {% else %}
                    <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'user:login' %}">Login</a>
                    {% endif %}
                    <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'post:create' %}">Create Post</a>
                    <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'post:feed' %}">View Posts</a>
                </div>
            </div>
        </div>
    </nav>
    

    {% block body %}

    {% endblock %}
</body>
</html>

user/templates/user/edit.html
{% extends 'user/base.html' %}
{% block body %}
<h1 class="text-2xl m-5 font-bold">Edit profile</h1>
<div class="container py-5 ">
    <form method="POST" class="bg-white shadow-md m-10 rounded px-2  pd-8 mb-4">
        {%csrf_token%}
        <div class="mb-3">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">First Name</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10">{{user_form.first_name}}</div>
        </div>
        <div class="mb-3">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Last name</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10">{{user_form.last_name}}</div>
        </div>
        <div class="mb-3">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Email</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10">{{user_form.email}}</div>
        </div>
        <div class="mb-3">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Image</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10">{{profile_form.photo}}</div>
        </div>
        
        <input type="submit" class="text-white bg-green-500 px-5 py-2 mb-3"></input>
    </form>
    
</div>

{% endblock %}

user/templates/user/index.html
{% extends 'user/base.html' %}
{% load static %}
{% block body %}
    <div class="flex mt-5 p-5 justify-center">
        <h2 class="text-3xl font-normal mb-2 text-green-500">My Post</h2>
    </div>

    <div class="grid mx-60 p-10 grid-cols-1">
        <!-- card start from here -->
        {% for post in posts %}
            
            <a href="#">
                <div class="rounded overflow-hidden w-[470px] bg-white shadow-lg">
                    <div class="user-container flex mx-5 my-5">
                        <img  class="h-12 w-12 rounded-full " src="{{profile.photo.url}}" alt="">
                        <div class="mx-2 my-2 font-bold">
                            <span class="text-indigo-500">{{post.user}}</span>
                        </div>
                    </div>
                    <div >
                        <img src="{{post.image.url}}" alt="">
                    </div>
                    <div class="px-6 py-4">
                        <div class="icon-container flex gap-3">
                            <img class="w-5 h-5" src="{% static 'user/images/like.png' %}" alt="">
                            <img class="w-5 h-5" src="{% static 'user/images/comment.png' %}" alt="">
                            <img class="w-5 h-5" src="{% static 'user/images/share.png' %}" alt="">
                        </div>
                    </div>
                </div>
                <div class="px-6 py-4">
                    <div class="font-bold text-xl mb-2">
                        {{post.title}}
                    </div>
                    <p class="text-gray-700 text-base">
                        {{post.caption}}
                    </p>
                </div>
                
            </a>

        {%endfor%}
        <!-- card end here -->
    </div>

{% endblock %}



       
    

user/templates/user/login.html
{% extends 'user/base.html' %}
{% block body %}
<h1 class="text-2xl m-10">Login User</h1>
<div class="container py-5 ">
    <form method="POST" class="bg-white shadow-md m-10 w-2/5 rounded px-8 pt-6 pd-8 mb-4">
        {%csrf_token%}
        <div class="mb-3">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">User Name</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10">{{form.username}}</div>
        </div>
        <div class="mb-3">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Password</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10">{{form.password}}</div>
        </div>
        
        <button type="submit" class="text-white bg-green-500 px-5 py-2 mb-3">Submit</button>
    </form>
    <p class="px-10 py-10">
        <a class="text-indigo-500" href="{% url 'user:password_reset' %}">Forget Password</a>
    </p>
    
</div>

{% endblock %}

user/templates/user/logout.html
<h1>Logout</h1>

user/templates/user/password_change_done.html
{% extends 'user/base.html' %}
{% block body %}
<h1 class="text-2xl m-5 font-bold">Password is changed.</h1>
{% endblock %}

user/templates/user/password_change_form.html
{% extends 'user/base.html' %}
{% block body %}
<h1 class="text-2xl m-5 font-bold">Edit profile</h1>
<div class="container py-5 ">
    <div class="error-container text-red-500 px-10">
        {% if form.errors %}
            {% for field in form %}
                {{field.errors}}
            {% endfor %}
        {% endif %}
    </div>  
    <form method="POST" class="bg-white shadow-md m-10 rounded px-2  pd-8 mb-4">
        {%csrf_token%}
        <div class="mb-3">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Old Password</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10">{{form.old_password}}</div>
        </div>
        <div class="mb-3">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">New Password</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10">{{form.new_password1}}</div>
        </div>
        <div class="mb-3">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Confirm Password</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10">{{form.new_password2}}</div>
        </div>
        
        <input type="submit" class="text-white bg-green-500 px-5 py-2 mb-3"></input>
    </form>
    
</div>

{% endblock %}

user/templates/user/password_reset_complete.html
{% extends 'user/base.html' %}
{% block body %}
<h1 class="text-2xl m-5 font-bold">Your password has been successfully reset</h1>
{% endblock %}

user/templates/user/password_reset_confirm.html
{% extends 'user/base.html' %}
{% block body %}
<h1 class="text-2xl m-5 font-bold">Edit profile</h1>
<div class="container py-5 ">
    <div class="error-container text-red-500 px-10">
        {% if form.errors %}
            {% for field in form %}
                {{field.errors}}
            {% endfor %}
        {% endif %}
    </div> 
    {% if validlink %} 
    <form method="POST" class="bg-white shadow-md m-10 rounded px-2  pd-8 mb-4">
        {%csrf_token%}
        <div class="mb-3">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">New Password</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10">{{form.new_password1}}</div>
        </div>
        <div class="mb-3">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Confirm Password</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10">{{form.new_password2}}</div>
        </div>
        
        <input type="submit" class="text-white bg-green-500 px-5 py-2 mb-3"></input>
    </form>
    {% else %}
    <h2>Password reset link is invalid</h2>
    {% endif %}
    
</div>

{% endblock %}

user/templates/user/password_reset_done.html
{% extends 'user/base.html' %}
{% block body %}
<h2 class="text-2xl m-5 font-bold">We have mailed you the password reset link</h2>
{% endblock %}

user/templates/user/password_reset_email.html
{% autoescape off %}
  Hello {{ user.email }}

  To initiate the password reset process for your {{ user.email }} Power-gurad App Account,
  click the link below:
  
  Click here to reset your password

  {{ protocol }}://{{ domain }}{% url 'user:password_reset_confirm' uidb64=uid token=token %}
  

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  Power-gurad
{% endautoescape %}

user/templates/user/password_reset_form.html
{% extends 'user/base.html' %}
{% block body %}
<h1 class="text-2xl m-5 font-bold">Password Reset Form</h1>
<div class="container py-5 ">
   
    <form method="POST" class="bg-white shadow-md m-10 rounded px-2  pd-8 mb-4">
        {%csrf_token%}
        <div class="mb-3">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Register Email</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10">{{form.email}}</div>
        </div>
        <input type="submit" class="text-white bg-green-500 px-5 py-2 mb-3"></input>
    </form>
    
</div>

{% endblock %}

user/templates/user/register.html
{% extends 'user/base.html' %}
{% block body %}
<h1 class="text-2xl m-10">Reguster User</h1>
<div class="container py-5 ">
    <form method="POST" class="bg-white shadow-md m-10 w-2/5 rounded px-8 pt-6 pd-8 mb-4">
        {%csrf_token%}
        <div class="mb-3">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">User Name</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10">{{form.username}}</div>
        </div>
        <div class="mb-3">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Email</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10">{{form.email}}</div>
        </div>
        <div class="mb-3">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Password</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10">{{form.password1}}</div>
        </div>
        <div class="mb-3">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Confirm Password</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10">{{form.password2}}</div>
        </div>
        
        <button type="submit" class="text-white bg-green-500 px-5 py-2 mb-3">Submit</button>
    </form>
    
</div>


{% endblock %}

user/templates/user/register_done.html
{% extends 'user/base.html' %}
{% block body %}
    <h1 class="text-2xl m-5 font-bold">Registretion Done</h1>
{% endblock %}